name: Deploy to Railway (Production)

on:
  push:
    branches: [mapper-and-validation]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven using production profile
        run: mvn clean package -Pprod